language: node_js
node_js:
  - 8.7.0
branches:
  only:
    - master
addons:
  ssh_known_hosts: headshot.ddns.net
before_install:
  - sudo apt-get -qq update && sudo apt-get -qq install chromium-browser chromium-chromedriver -y
  - npm install -g @angular/cli
  - npm install -g mocha
script:
  - openssl aes-256-cbc -K $encrypted_a30fa7ac3cd3_key -iv $encrypted_a30fa7ac3cd3_iv -in headshot.enc -out /tmp/headshot -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/headshot
  - ssh-add /tmp/headshot
  - pushd app-frontend
  - npm install
  - export CHROME_BIN=/usr/bin/chromium-browser && ng test --single-run --progress false
  - ng build --prod
  - pushd dist
  - tar cvfz /tmp/app-frontend.tar.gz ./*
  - popd
  - popd
  - scp /tmp/app-frontend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - rsh $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-frontend && rm -Rf ./*" || true
  - rsh $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-frontend && tar xvfz /tmp/app-frontend.tar.gz"
  - rsh $SERVER_USER@$SERVER_DNS "rm /tmp/app-frontend.tar.gz"
  - pushd app-backend
  - npm install
  - export NODE_ENV='test' && mocha tests.js && unset NODE_ENV
  - tar cvfz /tmp/app-backend.tar.gz index.js package.json package-lock.json
  - scp /tmp/app-backend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - rsh $SERVER_USER@$SERVER_DNS "sudo systemctl stop headshot.service" || true
  - rsh $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && rm -Rf ./*"
  - rsh $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && tar xvfz /tmp/app-backend.tar.gz"
  - rsh $SERVER_USER@$SERVER_DNS "rm /tmp/app-backend.tar.gz"
  - rsh $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && source ~/.nvm/nvm.sh && npm install --production"
  - rsh $SERVER_USER@$SERVER_DNS "sudo systemctl start headshot.service"
