language: node_js
node_js:
  - 8.7.0
script:
  - openssl aes-256-cbc -K $encrypted_a30fa7ac3cd3_key -iv $encrypted_a30fa7ac3cd3_iv -in headshot.enc -out /tmp/headshot -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/headshot
  - ssh-add /tmp/headshot
  - pushd app-frontend
  - npm install -g @angular/cli
  - npm install
  - ng build --prod
  - pushd dist
  - tar cvfz /tmp/app-frontend.tar.gz ./*
  - popd
  - popd
  # - $SCP /tmp/app-frontend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - scp -o StrictHostKeyChecking=no /tmp/app-frontend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-frontend && tar xvfz /tmp/app-frontend.tar.gz"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "rm /tmp/app-frontend.tar.gz"
