language: node_js
node_js:
  - 8.7.0
branches:
  only:
    - master
script:
  - openssl aes-256-cbc -K $encrypted_a30fa7ac3cd3_key -iv $encrypted_a30fa7ac3cd3_iv -in headshot.enc -out /tmp/headshot -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/headshot
  - ssh-add /tmp/headshot
  - sudo apt-get update && sudo apt-get install chromium-browser chromium-chromedriver -y
  - npm install -g @angular/cli
  - pushd app-frontend
  - npm install
  - export CHROME_BIN=/usr/bin/chromium-browser && ng test --single-run
  - ng build --prod
  - pushd dist
  - tar cvfz /tmp/app-frontend.tar.gz ./*
  - popd
  - popd
  - scp -o StrictHostKeyChecking=no /tmp/app-frontend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-frontend && rm -Rf ./*" || true
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-frontend && tar xvfz /tmp/app-frontend.tar.gz"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "rm /tmp/app-frontend.tar.gz"
  - pushd app-backend
  #install npm dependencies
  #run tests
  # - tar cvfz /tmp/app-backend.tar.gz app-core/ app-server/ conf.js index.js mongoInMemory.js package.json
  - tar cvfz /tmp/app-backend.tar.gz conf.js index.js mongoInMemory.js package.json
  - scp -o StrictHostKeyChecking=no /tmp/app-backend.tar.gz $SERVER_USER@$SERVER_DNS:/tmp
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "sudo systemctl stop headshot.service"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && rm -Rf ./*"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && tar xvfz /tmp/app-backend.tar.gz"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "rm /tmp/app-backend.tar.gz"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "cd /srv/headshot/app-backend && source ~/.nvm/nvm.sh && npm install --production"
  - rsh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_DNS "sudo systemctl start headshot.service"
